version: "3.7"

services:
  db:
    container_name: db
    restart: always
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432      
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project
  web:
    container_name: web
    restart: always
    build: .
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
  web-server:
    container_name: nginx
    image: nginx:1.16.1-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  web-server: